//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Port
    {
        public int PortId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lon { get; set; }
        public Nullable<int> VesselId { get; set; }
    
        public virtual Vessel Vessel { get; set; }
    }
}
