//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VesselMovment
    {
        public int MovmentId { get; set; }
        public Nullable<int> Course { get; set; }
        public Nullable<int> Radio { get; set; }
        public Nullable<int> Speed { get; set; }
        public string ShipStatus { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lon { get; set; }
        public Nullable<int> VesselID { get; set; }
    
        public virtual Vessel Vessel { get; set; }
    }
}
